#!/bin/bash

# GitHub API URL
API_URL="api.github.com"

# GitHub username and personal access token 
USERNAME=$username
TOKEN=$token

# User and Repository information
REPO_OWNER=$1
REPO_NAME=$2

# Function to make a GET request to thhe Github API
function github_api_get{
    local endpoint="$1"
    local url="${API-URL}/${endpoint}"

    # send a GET request to the GitHub API with authentication
    curl -s -u "${USERNAME}:${TOKEN}" "URL"
}

# Function to list users with read access to the repository
function list_users_with_read_access {
     local endpoint="repos/${REPO_OWNER}/{REPO_NAME}/collaborators"

     # Fetch the list of collaborators with read access
     collaborators="$(github_api_get "$endpoint" | jq -r '.[] | select(.permission.pull == true) | .login')"

     # Display the list of collaborators with read access
     if [[ -z "$collabrators" ]]; then 
         echo "No users with read access found for ${REPO_OWNER}/${REPO_NAME}"
     else
         echo "User with read access to ${REPO_OWNER}/${REPO_NAME}:"
         echo "$collaborators"
     fi
}

# Main script

echo "Listing users with read access to ${REPO_OWNER}/${REPO_NAME}..."
list_users_with_read_access
