#!/bin/bash

# GitHub API URL
API_URL="api.github.com"

# GitHub username and personal access token 
USERNAME=$username
TOKEN=$tokwen

# User and Repository  information
REPO_OWNER=$1
REPO_NAME=$2

# Function to make a GET request to thhe Github API
function 
